export const WRITING_PROMPTS = [
  "Describe a place you have never visited but feel you know well.",
  "Write about a small habit that changed how your mornings feel.",
  "Someone returns a borrowed item years later than expected. What do they say?",
  "Explain a complicated idea to someone who has five minutes and no background in it.",
  "A character finds a note in a book they did not buy. What does it say?",
  "Describe the last conversation you wish you had handled differently.",
  "Write one paragraph about a sound you associate with home.",
  "A city bus breaks down in an unfamiliar neighborhood. What happens next?",
  "Tell the story of an object that outlasted its original owner.",
  "Describe a meal that meant more than the food on the plate.",
  "Someone learns a secret that was never meant for them. How do they react?",
  "Write about the moment before a decision you cannot take back.",
  "Describe a landscape at the hour when most people are asleep.",
  "A letter arrives with no return address and no stamp. Open it.",
  "Explain why a common saying is wrong — or more right than people admit.",
  "Write about two people who disagree but still respect each other.",
  "Describe a room the way a stranger would notice it in the first thirty seconds.",
  "Someone keeps a promise that costs them more than they expected.",
  "Write about a technology you use daily without fully understanding it.",
  "A child asks a question that an adult cannot answer honestly.",
  "Describe the weather on a day that changed your plans entirely.",
  "Write about a friendship that started with a misunderstanding.",
  "Someone must deliver bad news as gently as possible. Draft what they say.",
  "Describe a street you walked once and never forgot.",
  "Write about learning something you thought you already knew.",
  "A photograph captures something the photographer did not intend. Describe it.",
  "Explain what patience looks like in a world that rewards speed.",
  "Write about a gift that was perfectly wrong — or perfectly right.",
  "Someone hears their name called in a crowd, but no one is looking at them.",
  "Describe the feeling of returning somewhere after a long absence.",
] as const;
