export interface TopicLanguageEntry {
  id: string;
  title: string;
  advantages: string[];
  disadvantages: string[];
  usefulNouns: string[];
  usefulVerbs: string[];
  exampleSentences: string[];
}

export const TOPIC_LANGUAGE_BANK: TopicLanguageEntry[] = [
  {
    id: "education",
    title: "Education",
    advantages: [
      "improve academic performance",
      "enhance learning outcomes",
      "broaden knowledge",
      "develop critical thinking",
      "foster creativity",
      "promote lifelong learning",
      "increase employability",
      "provide equal opportunities",
      "strengthen problem-solving skills",
      "support personal development",
    ],
    disadvantages: [
      "increase academic pressure",
      "widen the achievement gap",
      "reduce face-to-face interaction",
      "limit practical experience",
      "create financial burden",
      "encourage rote memorisation",
      "overwhelm students",
      "diminish motivation",
      "restrict access in rural areas",
      "undermine traditional teaching methods",
    ],
    usefulNouns: ["curriculum", "literacy", "enrolment", "pedagogy", "attainment"],
    usefulVerbs: ["educate", "assess", "motivate", "equip", "standardise"],
    exampleSentences: [
      "A well-designed curriculum can significantly improve academic performance.",
      "Online platforms broaden knowledge but may reduce face-to-face interaction.",
    ],
  },
  {
    id: "technology",
    title: "Technology",
    advantages: [
      "improve productivity",
      "enhance communication",
      "streamline workflows",
      "reduce manual errors",
      "enable remote collaboration",
      "accelerate innovation",
      "increase efficiency",
      "provide instant access to information",
      "automate repetitive tasks",
      "support data-driven decisions",
    ],
    disadvantages: [
      "increase screen dependency",
      "reduce interpersonal skills",
      "create security risks",
      "widen the digital divide",
      "displace workers",
      "encourage information overload",
      "undermine privacy",
      "disrupt traditional industries",
      "reduce attention spans",
      "generate electronic waste",
    ],
    usefulNouns: ["automation", "connectivity", "innovation", "cybersecurity", "efficiency"],
    usefulVerbs: ["automate", "digitise", "integrate", "upgrade", "disrupt"],
    exampleSentences: [
      "Modern technology improves productivity by automating routine administrative tasks.",
      "Excessive screen time may reduce interpersonal skills among young people.",
    ],
  },
  {
    id: "artificial-intelligence",
    title: "Artificial Intelligence",
    advantages: [
      "enhance decision-making",
      "improve diagnostic accuracy",
      "automate complex processes",
      "increase operational efficiency",
      "personalise user experiences",
      "accelerate research",
      "reduce human error",
      "optimise resource allocation",
      "support medical breakthroughs",
      "transform customer service",
    ],
    disadvantages: [
      "displace jobs",
      "raise ethical concerns",
      "increase bias in algorithms",
      "reduce human oversight",
      "threaten data privacy",
      "create accountability gaps",
      "widen inequality",
      "undermine creative professions",
      "generate misinformation",
      "require heavy energy consumption",
    ],
    usefulNouns: ["algorithm", "automation", "machine learning", "ethics", "innovation"],
    usefulVerbs: ["automate", "analyse", "predict", "optimise", "replace"],
    exampleSentences: [
      "Artificial intelligence can enhance decision-making in healthcare diagnostics.",
      "The rapid adoption of AI may displace jobs in traditional manufacturing sectors.",
    ],
  },
  {
    id: "television",
    title: "Television",
    advantages: [
      "provide educational content",
      "raise public awareness",
      "promote cultural exchange",
      "offer affordable entertainment",
      "disseminate news quickly",
      "inspire creativity",
      "connect communities",
      "support language learning",
      "document historical events",
      "encourage family bonding",
    ],
    disadvantages: [
      "encourage sedentary behaviour",
      "reduce reading habits",
      "promote unrealistic expectations",
      "increase exposure to violence",
      "diminish critical thinking",
      "disrupt sleep patterns",
      "reduce outdoor activity",
      "spread misleading advertising",
      "limit social interaction",
      "consume excessive time",
    ],
    usefulNouns: ["broadcasting", "viewership", "media literacy", "entertainment", "advertising"],
    usefulVerbs: ["broadcast", "influence", "entertain", "inform", "shape"],
    exampleSentences: [
      "Educational television programmes can raise public awareness about health issues.",
      "Excessive viewing may encourage sedentary behaviour among children.",
    ],
  },
  {
    id: "environment",
    title: "Environment",
    advantages: [
      "protect biodiversity",
      "reduce carbon emissions",
      "conserve natural resources",
      "improve air quality",
      "promote sustainable development",
      "mitigate climate change",
      "preserve ecosystems",
      "encourage renewable energy",
      "support public health",
      "strengthen community resilience",
    ],
    disadvantages: [
      "increase implementation costs",
      "disrupt industries",
      "create economic uncertainty",
      "require lifestyle changes",
      "limit economic growth",
      "generate political conflict",
      "burden developing nations",
      "reduce short-term profits",
      "complicate supply chains",
      "demand significant investment",
    ],
    usefulNouns: ["sustainability", "emissions", "biodiversity", "conservation", "pollution"],
    usefulVerbs: ["conserve", "pollute", "mitigate", "degrade", "preserve"],
    exampleSentences: [
      "Renewable energy policies can significantly reduce carbon emissions.",
      "Strict environmental regulations may disrupt traditional industries in the short term.",
    ],
  },
  {
    id: "health",
    title: "Health",
    advantages: [
      "improve life expectancy",
      "enhance quality of life",
      "reduce healthcare costs",
      "prevent chronic disease",
      "promote mental wellbeing",
      "increase workplace productivity",
      "strengthen immune systems",
      "encourage healthy habits",
      "expand access to care",
      "support early diagnosis",
    ],
    disadvantages: [
      "increase medical expenses",
      "create access inequality",
      "overburden healthcare systems",
      "raise insurance premiums",
      "promote overmedication",
      "generate long waiting times",
      "cause lifestyle pressure",
      "spread misinformation",
      "neglect preventive care",
      "widen urban-rural gaps",
    ],
    usefulNouns: ["wellbeing", "prevention", "treatment", "nutrition", "immunity"],
    usefulVerbs: ["diagnose", "prevent", "treat", "recover", "vaccinate"],
    exampleSentences: [
      "Regular exercise can significantly improve life expectancy and mental wellbeing.",
      "Rising medical expenses create access inequality for low-income families.",
    ],
  },
  {
    id: "exercise",
    title: "Exercise",
    advantages: [
      "improve cardiovascular health",
      "reduce stress levels",
      "boost mental clarity",
      "strengthen muscles",
      "enhance sleep quality",
      "increase energy levels",
      "prevent obesity",
      "build discipline",
      "promote social connection",
      "support immune function",
    ],
    disadvantages: [
      "increase injury risk",
      "consume valuable time",
      "require financial cost",
      "cause physical exhaustion",
      "create performance pressure",
      "lead to overtraining",
      "discourage beginners",
      "depend on facilities",
      "worsen existing conditions",
      "reduce leisure time",
    ],
    usefulNouns: ["fitness", "endurance", "recovery", "motivation", "stamina"],
    usefulVerbs: ["train", "stretch", "recover", "compete", "condition"],
    exampleSentences: [
      "Regular exercise improves cardiovascular health and reduces stress levels.",
      "Intensive training without proper guidance may increase injury risk.",
    ],
  },
  {
    id: "working-from-home",
    title: "Working From Home",
    advantages: [
      "improve work-life balance",
      "reduce commuting time",
      "increase flexibility",
      "lower transport costs",
      "enhance productivity",
      "reduce office overhead",
      "support family commitments",
      "decrease carbon footprint",
      "attract global talent",
      "enable focused work",
    ],
    disadvantages: [
      "reduce team collaboration",
      "blur work-life boundaries",
      "increase isolation",
      "limit career visibility",
      "create communication gaps",
      "reduce mentoring opportunities",
      "depend on reliable technology",
      "weaken company culture",
      "distract from household duties",
      "complicate performance monitoring",
    ],
    usefulNouns: ["flexibility", "commuting", "productivity", "collaboration", "isolation"],
    usefulVerbs: ["commute", "collaborate", "telecommute", "supervise", "coordinate"],
    exampleSentences: [
      "Remote work improves work-life balance by eliminating daily commuting.",
      "Working from home may reduce team collaboration and weaken company culture.",
    ],
  },
  {
    id: "social-media",
    title: "Social Media",
    advantages: [
      "facilitate global communication",
      "promote business growth",
      "raise social awareness",
      "connect distant communities",
      "share knowledge quickly",
      "support grassroots movements",
      "enable creative expression",
      "provide networking opportunities",
      "disseminate emergency information",
      "encourage civic engagement",
    ],
    disadvantages: [
      "spread misinformation",
      "increase cyberbullying",
      "reduce attention spans",
      "promote unrealistic comparisons",
      "undermine privacy",
      "encourage addiction",
      "polarise public debate",
      "diminish face-to-face skills",
      "expose users to fraud",
      "affect mental health",
    ],
    usefulNouns: ["engagement", "influencer", "connectivity", "privacy", "virality"],
    usefulVerbs: ["share", "influence", "connect", "broadcast", "moderate"],
    exampleSentences: [
      "Social media facilitates global communication and promotes business growth.",
      "Unregulated platforms may spread misinformation and affect mental health.",
    ],
  },
  {
    id: "tourism",
    title: "Tourism",
    advantages: [
      "boost local economies",
      "create employment",
      "promote cultural exchange",
      "preserve heritage sites",
      "generate foreign revenue",
      "support small businesses",
      "improve infrastructure",
      "raise international awareness",
      "encourage environmental conservation",
      "strengthen diplomatic ties",
    ],
    disadvantages: [
      "damage ecosystems",
      "increase pollution",
      "raise living costs",
      "erode local culture",
      "create seasonal unemployment",
      "overcrowd destinations",
      "exploit workers",
      "strain public services",
      "encourage commercialisation",
      "disrupt local communities",
    ],
    usefulNouns: ["hospitality", "heritage", "infrastructure", "sustainability", "revenue"],
    usefulVerbs: ["attract", "promote", "preserve", "commercialise", "overcrowd"],
    exampleSentences: [
      "Sustainable tourism can boost local economies while preserving heritage sites.",
      "Mass tourism may damage ecosystems and raise living costs for residents.",
    ],
  },
  {
    id: "government",
    title: "Government",
    advantages: [
      "provide public services",
      "maintain law and order",
      "redistribute wealth",
      "invest in infrastructure",
      "protect national security",
      "regulate markets",
      "fund education",
      "support vulnerable groups",
      "coordinate disaster response",
      "promote economic stability",
    ],
    disadvantages: [
      "increase bureaucracy",
      "raise taxation",
      "limit individual freedom",
      "slow decision-making",
      "encourage corruption",
      "waste public funds",
      "create political division",
      "burden businesses",
      "reduce innovation",
      "fail to meet citizen expectations",
    ],
    usefulNouns: ["regulation", "taxation", "policy", "governance", "accountability"],
    usefulVerbs: ["regulate", "fund", "legislate", "subsidise", "enforce"],
    exampleSentences: [
      "Effective government policy can invest in infrastructure and fund education.",
      "Excessive bureaucracy may slow decision-making and waste public funds.",
    ],
  },
  {
    id: "transport",
    title: "Transport",
    advantages: [
      "improve connectivity",
      "reduce travel time",
      "boost economic activity",
      "enhance mobility",
      "support trade",
      "create employment",
      "reduce isolation",
      "enable urban development",
      "facilitate emergency access",
      "promote tourism",
    ],
    disadvantages: [
      "increase pollution",
      "cause traffic congestion",
      "raise infrastructure costs",
      "contribute to noise",
      "consume energy",
      "displace communities",
      "endanger pedestrians",
      "widen urban sprawl",
      "depend on fossil fuels",
      "strain public budgets",
    ],
    usefulNouns: ["infrastructure", "congestion", "mobility", "emissions", "connectivity"],
    usefulVerbs: ["commute", "transport", "congest", "navigate", "commence"],
    exampleSentences: [
      "Efficient public transport improves connectivity and reduces travel time.",
      "Rising car ownership increases pollution and causes traffic congestion.",
    ],
  },
  {
    id: "online-learning",
    title: "Online Learning",
    advantages: [
      "offer flexible schedules",
      "reduce education costs",
      "expand global access",
      "personalise learning paths",
      "provide recorded content",
      "support remote students",
      "enable self-paced study",
      "integrate multimedia tools",
      "connect expert instructors",
      "accommodate working adults",
    ],
    disadvantages: [
      "reduce student engagement",
      "limit hands-on practice",
      "require self-discipline",
      "widen the digital divide",
      "decrease social interaction",
      "raise cheating concerns",
      "depend on technology",
      "reduce teacher feedback",
      "cause screen fatigue",
      "lower completion rates",
    ],
    usefulNouns: ["flexibility", "engagement", "accessibility", "platform", "enrolment"],
    usefulVerbs: ["enrol", "stream", "personalise", "engage", "complete"],
    exampleSentences: [
      "Online learning offers flexible schedules and expands global access to education.",
      "Virtual classrooms may reduce student engagement and limit hands-on practice.",
    ],
  },
  {
    id: "universities",
    title: "Universities",
    advantages: [
      "advance research",
      "produce skilled graduates",
      "drive innovation",
      "attract international talent",
      "strengthen economies",
      "foster critical thinking",
      "build professional networks",
      "preserve academic knowledge",
      "support community development",
      "promote cultural diversity",
    ],
    disadvantages: [
      "increase student debt",
      "limit practical training",
      "create access barriers",
      "prioritise theory over skills",
      "burden taxpayers",
      "produce unemployed graduates",
      "encourage grade inflation",
      "depend on rankings",
      "neglect vocational pathways",
      "face funding cuts",
    ],
    usefulNouns: ["tuition", "research", "accreditation", "enrolment", "graduation"],
    usefulVerbs: ["research", "accredit", "graduate", "fund", "specialise"],
    exampleSentences: [
      "Universities advance research and produce skilled graduates for the economy.",
      "Rising tuition fees increase student debt and create access barriers.",
    ],
  },
  {
    id: "advertising",
    title: "Advertising",
    advantages: [
      "inform consumers",
      "stimulate competition",
      "support media industries",
      "create brand awareness",
      "drive economic growth",
      "fund free content",
      "introduce new products",
      "enable market choice",
      "generate employment",
      "encourage innovation",
    ],
    disadvantages: [
      "manipulate consumer behaviour",
      "target vulnerable groups",
      "promote materialism",
      "mislead audiences",
      "increase product costs",
      "invade privacy",
      "encourage impulsive buying",
      "normalise unhealthy products",
      "reduce attention quality",
      "create unrealistic standards",
    ],
    usefulNouns: ["brand", "consumerism", "targeting", "campaign", "persuasion"],
    usefulVerbs: ["advertise", "persuade", "target", "promote", "brand"],
    exampleSentences: [
      "Ethical advertising informs consumers and stimulates healthy market competition.",
      "Aggressive marketing may manipulate consumer behaviour and promote materialism.",
    ],
  },
];

export function getTopicById(id: string): TopicLanguageEntry | undefined {
  return TOPIC_LANGUAGE_BANK.find((topic) => topic.id === id);
}
